internal.lb.uri: http://localhost
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: https://www.googleapis.com/oauth2/v3/certs
  cloud:
    gateway:
      routes:
        - id: product-microservice
          uri: ${internal.lb.uri}:8081
          predicates:
            - Path=/product-microservice/**
          filters:
            - RewritePath=/product-microservice/(?<path>.*), /$\{path}
